### PR TITLE
Add Project Folder with each class

### PR DESCRIPTION
**Pull request by bugg86**

### CODE REVIEW

**Comment by scday** [comment]
Great job getting started! Check the updated readme.md file for week 7 in-class activity

**Comment by scday** [comment]
@jamisonv93 @bugg86 What are you all using to work together on this assignment? The desktop application or your command prompt/terminal?

**Comment by jamisonvalentine** [comment]
I don't think we used either to get started. We were having trouble getting everyone in the same group/team, so that's about as far as we made it.

**Comment by scday** [comment]
Why is that? @jamisonv93 . What happened?

**Comment by jamisonvalentine** [comment]
@scday Just a simple oversight. We hadn't created a new repo for Week 7 for everyone to join.

**Comment by scday** [comment]
Ok no problem. @jamisonv93

**Pull request merged**
